service: appsync-event-bridge

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x

custom:
  appSync:
    name: appsync-many-to-many
    authenticationType: API_KEY

    logConfig:
      level: ALL

    functionConfigurations:
      - dataSource: users
        name: getGroupUsers
      - dataSource: users
        name: getUsers
      

    mappingTemplates:
      - kind: PIPELINE
        dataSource: getGroupUsers
        type: Query
        field: getGroupUsers
        functions:
          - getGroupUsers
          - getUsers

    dataSources:
      - type: AMAZON_DYNAMODB
        name: users
        config:
          tableName: !Ref Users

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
